name: Docker CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and test React app
        run: |
          docker build -t daniel1mor3055/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true daniel1mor3055/react-test npm test

      - name: Build Docker images
        run: |
          docker build -t daniel1mor3055/multi-client ./client
          docker build -t daniel1mor3055/multi-server ./server
          docker build -t daniel1mor3055/multi-worker ./worker

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_ID }}" --password-stdin

      - name: Push Docker images to Docker Hub
        run: |
          docker push daniel1mor3055/multi-client
          docker push daniel1mor3055/multi-server
          docker push daniel1mor3055/multi-worker
